In [1]:
import torch

In [2]:
torch.__version__

'2.3.1'

In [4]:
x = torch.empty(5,3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
x = torch.rand(5,3)
x

tensor([[0.2833, 0.3835, 0.4613],
        [0.1467, 0.0523, 0.4607],
        [0.1879, 0.2785, 0.3923],
        [0.5208, 0.5243, 0.8274],
        [0.2486, 0.9265, 0.0292]])

In [6]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [9]:
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[-6.5470e-01,  2.3844e-01, -7.7238e-01],
        [ 1.0747e+00, -1.8180e+00, -1.3027e-01],
        [ 5.7038e-01,  8.6213e-04,  1.5566e+00],
        [ 1.8133e+00,  3.4158e-01, -6.2059e-02],
        [ 3.8745e-01, -2.2337e+00,  7.7541e-01]])

In [10]:
x.size()

torch.Size([5, 3])

In [12]:
x.shape

torch.Size([5, 3])

In [13]:
y = torch.rand(5,3)

In [14]:
torch.add(x,y)

tensor([[-0.2988,  0.6443, -0.7343],
        [ 1.5215, -0.9360,  0.2800],
        [ 0.8088,  0.2941,  2.4735],
        [ 2.1588,  1.0796, -0.0581],
        [ 1.1757, -2.0665,  0.9599]])

In [15]:
x[:, 1]

tensor([ 2.3844e-01, -1.8180e+00,  8.6213e-04,  3.4158e-01, -2.2337e+00])

In [17]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [18]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [19]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)