In [1]:
import torch

In [2]:
x = torch.randn(3,4,requires_grad=True,)
x

tensor([[ 0.3011, -1.1278,  1.2476,  0.8900],
        [ 0.3806, -0.0420,  0.3782,  0.1370],
        [-0.5828,  0.8441,  2.0475,  0.7757]], requires_grad=True)

In [ ]:
x = torch.randn(
    3,
    4,
)
x.requires_grad = True

In [3]:
b = torch.randn(3,4, requires_grad=True)

In [5]:
t = x + b
t

tensor([[ 0.2101, -2.2307,  1.9303,  0.7288],
        [-0.0283,  1.6458,  0.1578,  0.4596],
        [-1.2680,  2.1230,  1.6342, -0.0296]], grad_fn=<AddBackward0>)

In [6]:
y = t.sum()
y

tensor(5.3328, grad_fn=<SumBackward0>)

In [7]:
y.backward()

In [8]:
b.grad

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
x.requires_grad, b.requires_grad, t.requires_grad

(True, True, True)

In [10]:
x = torch.rand(1)
w = torch.rand(1, requires_grad=True)
b = torch.rand(1, requires_grad=True)

y = w * x
z = y + b

In [11]:
x.requires_grad, b.requires_grad, w.requires_grad, y.requires_grad,

(False, True, True, True)

In [12]:
x.is_leaf, b.is_leaf, w.is_leaf, y.is_leaf,

(True, True, True, False)