In [1]:
import torch
from torch import tensor

### Scalar

In [2]:
x = tensor(42.)
x

tensor(42.)

In [3]:
x.dim()

0

In [4]:
x.item()

42.0

### Vector

In [5]:
v = tensor(
  [1.5, -0.5, 3.0]
)
v

tensor([ 1.5000, -0.5000,  3.0000])

In [6]:
v.dim()

1

In [7]:
v.size()

torch.Size([3])

### Matrix

In [8]:
M = tensor(
  [
    [1., 2.],
    [3., 4.],
  ]
)

In [9]:
# 相乘矩阵
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])

In [10]:
M * M

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [11]:
tensor([1.,0.]).matmul(M)

tensor([1., 2.])

In [12]:
tensor([1., 2.]).matmul(M)

tensor([ 7., 10.])